# Dependencies
markdown:         kramdown
highlighter:      pygments

plugins:
  - jekyll-gist
  - jekyll-paginate


# Enable safe mode
safe: true

# Whitelist plugins under safe mode.
# Note that `some-other-jekyll-plugin` is not listed here. Therefore,
# it will not be loaded under safe mode.
whitelist:
  - jekyll-gist
  - jekyll-paginate


# Permalinks
permalink:        pretty


# Setup
title:            Al Astudillo
tagline:          'Programming and love'
description:      'Programming, photography, writing and love.'
url:              al.astudillo.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/poole/hyde
